### ISSUE TITLE
Классы вынести в библиотеку, добавить операций с ними в Program.cs

### ISSUE THREAD

**Issue by alexeychernykh** [RusRonin/university_model#1]
https://github.com/RusRonin/university_model/blob/dc7b5a47ee50f0ef7435f7fc775fba6e03ed74c7/UniversityModel/Program.cs#L9

Вместо программы заглушка, нужно чтобы программа запускалась и делала некоторые полезные операции в университете.

**Comment by RusRonin** [comment]
Кинул пул реквест
